name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      SONAR_SCANNER_VERSION: 4.6.2.2472      
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: build-sonar
      run: |
        echo "Downloading Sonar Scanner with Env version here"      
        curl -LO https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${{ env.SONAR_SCANNER_VERSION}}-linux.zip
        sudo apt install unzip
        echo "Unzipping"
        sudo unzip -q sonar-scanner-cli-${{ env.SONAR_SCANNER_VERSION}}-linux.zip -d /usr/local/bin/sonar
        echo "Running Staticcode analysis"
        /usr/local/bin/sonar/sonar-scanner-${{ env.SONAR_SCANNER_VERSION}}-linux/bin/sonar-scanner \
           -Dsonar.projectKey=tempone \
           -Dsonar.sources=. \
           -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
           -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
           -Dsonar.exclusions=./vendor/golang.org/x/sys/unix/gccgo_c.c
           
