name: rootdir

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      SONAR_SCANNER_VERSION: 4.6.2.2472      
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: display rootdir
      run: |
        echo "${{ github.workspace }}"
        
    - name: Push images
      uses: docker/build-push-action@v2
        tags: |
            sridhar:test-two
      run: |
        docker images    
